### ISSUE TITLE
Extension should really use TypeScript

### ISSUE THREAD

**Issue by glennsarti** [potatoqualitee/vscode-dbatools-search#4]
While this extension is currently very simple;

* Most VSCode extensions are written using TypeScript
* All of the example code etc uses TypeScript.
* Using a strongly typed language means you have better development experience etc.

**Comment by potatoqualitee** [comment]
This is a bit of a side project so it's hard for me to jump in and learn typescript for it cuz i'm not used to strongly typed languages. but perhaps it's somethign i could explore when i'm procrastinating another big deadline ;)

**Comment by potatoqualitee** [comment]
Not procrastinating, but had some time to explore TypeScript 😇
