### ISSUE TITLE
Feature Request: Use the WebView API instead of calling external browser

### ISSUE THREAD

**Issue by glennsarti** [potatoqualitee/vscode-dbatools-search#5]
The VSCode WebView API is kind of designed for displaying HTML based content easily within VSCode itself.  Perhaps instead of calling out to an external browser, the extension should use the WebView API? [1]

[1] https://code.visualstudio.com/docs/extensions/webview

**Comment by potatoqualitee** [comment]
Mmm this isn't the experience I would like for myself, so for the primary use case, I don't think it's a good default. However, I heard you can run VS Code on Azure, and I think it'd be appropriate there. We could do an `if azure then use webapi or setting.usewebapi else default browser` 👍

**Comment by kien5436** [comment]
Let be VSCode as it is, code editor, not browser. When I search for something, I likely open a ton of tabs, so open search result in webview will be a nightmare

**Comment by potatoqualitee** [comment]
Going to close this one, as I just rewrote the extension in TS and I'm still not into adding an optional web panel 😇  If I get the urge, I'll reopen.
