### ISSUE TITLE
Increment required VS Code version

### ISSUE THREAD

**Issue by glennsarti** [potatoqualitee/vscode-dbatools-search#6]
The minimum VSCode version is currently set to 1.11 which is very old.  This extension can probably enforce v1.20.0+ safely and can take advantage of new VSCode API features e.g. WebView API.

https://github.com/potatoqualitee/vscode-dbatools-search/blob/2d9728fafd3bdd421e2a1c5867097842e71d40f5/package.json#L9

**Comment by potatoqualitee** [comment]
thanks good idea! done
