### ISSUE TITLE
Feature Request : Auto figure out text selection based on cursor position

### ISSUE THREAD

**Issue by glennsarti** [potatoqualitee/vscode-dbatools-search#8]
Currently the extension doesn't show the menu items if text is not selected.

Instead would it not be possible to auto select text based on cursor position if none is selected e.g. in the readme it shows

`if ($PSCmdlet.ShouldProcess($ag.ParentName...)`

So if the cursor is in the `h` of `ShouldProcess` the extension should figure out the text selection is actually `$PSCmdlet.ShouldProcess`  (because the left and right extreme characters don't match a regex e.g. [a-zA-z0-9.$-_]) and then search on that.

**Comment by potatoqualitee** [comment]
I agree, will have to research how to make it search on the mildly highlighted term instead of having to be so explicit

**Comment by potatoqualitee** [comment]
I think this'll in part be `getWordRangeAtPosition`

**Comment by potatoqualitee** [comment]
Thanks, Chrissy! That is helpful 😅
